[package]
name = "speed_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.7", features = ["blocking", "json"] }
tokio = { version = "1.14.0", features = ["full"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.74"
tokio-tungstenite = "0.17.1"
futures = "0.1"
futures-util = "0.3.21"
futures-channel = "0.3"
url = "2.2.2"

[dev-dependencies]
